package com.quangnt.entities;
// Generated Dec 17, 2021 8:43:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "Categories",
        schema = "dbo",
        catalog = "MyStockDB"
)
public class Category implements java.io.Serializable {

    private int categoryId;
    private String categoryName;
    private Set<Product> productses = new HashSet<Product>(0);

    public Category() {
    }

    public Category(int categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }

    public Category(int categoryId, String categoryName, Set<Product> productses) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.productses = productses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CategoryID", unique = true, nullable = false)
    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "CategoryName", nullable = false)
    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
    public Set<Product> getProductses() {
        return this.productses;
    }

    public void setProductses(Set<Product> productses) {
        this.productses = productses;
    }

}
