package com.quangnt.entities;
// Generated Dec 17, 2021 8:43:25 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "Products",
         schema = "dbo",
         catalog = "MyStockDB"
)
public class Product implements java.io.Serializable {

    private int productId;
    private Category categories;
    private String productName;
    private double unitPrice;
    private int unitsInStock;
    private String status;

    public Product() {
    }

    public Product(Category categories, String productName, double unitPrice, int unitsInStock, String status) {
        this.categories = categories;
        this.productName = productName;
        this.unitPrice = unitPrice;
        this.unitsInStock = unitsInStock;
        this.status = status;
    }

    public Product(int productId, String productName, double unitPrice, int unitsInStock) {
        this.productId = productId;
        this.productName = productName;
        this.unitPrice = unitPrice;
        this.unitsInStock = unitsInStock;
    }

    public Product(int productId, Category categories, String productName, double unitPrice, int unitsInStock, String status) {
        this.productId = productId;
        this.categories = categories;
        this.productName = productName;
        this.unitPrice = unitPrice;
        this.unitsInStock = unitsInStock;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ProductID", unique = true, nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CategoryID")
    public Category getCategories() {
        return this.categories;
    }

    public void setCategories(Category categories) {
        this.categories = categories;
    }

    @Column(name = "ProductName", nullable = false)
    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    @Column(name = "UnitPrice", nullable = false, scale = 4)
    public double getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

    @Column(name = "UnitsInStock", nullable = false)
    public int getUnitsInStock() {
        return this.unitsInStock;
    }

    public void setUnitsInStock(int unitsInStock) {
        this.unitsInStock = unitsInStock;
    }

    @Column(name = "Status")
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
